# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/autumn/Projects/SnolfMania

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/autumn/Projects/SnolfMania

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/autumn/Projects/SnolfMania/CMakeFiles /home/autumn/Projects/SnolfMania//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/autumn/Projects/SnolfMania/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SnolfMania

# Build rule for target.
SnolfMania: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SnolfMania
.PHONY : SnolfMania

# fast build rule for target.
SnolfMania/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/build
.PHONY : SnolfMania/fast

GameAPI/C/GameAPI/Game.o: GameAPI/C/GameAPI/Game.c.o
.PHONY : GameAPI/C/GameAPI/Game.o

# target to build an object file
GameAPI/C/GameAPI/Game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/GameAPI/C/GameAPI/Game.c.o
.PHONY : GameAPI/C/GameAPI/Game.c.o

GameAPI/C/GameAPI/Game.i: GameAPI/C/GameAPI/Game.c.i
.PHONY : GameAPI/C/GameAPI/Game.i

# target to preprocess a source file
GameAPI/C/GameAPI/Game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/GameAPI/C/GameAPI/Game.c.i
.PHONY : GameAPI/C/GameAPI/Game.c.i

GameAPI/C/GameAPI/Game.s: GameAPI/C/GameAPI/Game.c.s
.PHONY : GameAPI/C/GameAPI/Game.s

# target to generate assembly for a file
GameAPI/C/GameAPI/Game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/GameAPI/C/GameAPI/Game.c.s
.PHONY : GameAPI/C/GameAPI/Game.c.s

SnolfMania/Objects/HUD.o: SnolfMania/Objects/HUD.c.o
.PHONY : SnolfMania/Objects/HUD.o

# target to build an object file
SnolfMania/Objects/HUD.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/HUD.c.o
.PHONY : SnolfMania/Objects/HUD.c.o

SnolfMania/Objects/HUD.i: SnolfMania/Objects/HUD.c.i
.PHONY : SnolfMania/Objects/HUD.i

# target to preprocess a source file
SnolfMania/Objects/HUD.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/HUD.c.i
.PHONY : SnolfMania/Objects/HUD.c.i

SnolfMania/Objects/HUD.s: SnolfMania/Objects/HUD.c.s
.PHONY : SnolfMania/Objects/HUD.s

# target to generate assembly for a file
SnolfMania/Objects/HUD.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/HUD.c.s
.PHONY : SnolfMania/Objects/HUD.c.s

SnolfMania/Objects/Player.o: SnolfMania/Objects/Player.c.o
.PHONY : SnolfMania/Objects/Player.o

# target to build an object file
SnolfMania/Objects/Player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Player.c.o
.PHONY : SnolfMania/Objects/Player.c.o

SnolfMania/Objects/Player.i: SnolfMania/Objects/Player.c.i
.PHONY : SnolfMania/Objects/Player.i

# target to preprocess a source file
SnolfMania/Objects/Player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Player.c.i
.PHONY : SnolfMania/Objects/Player.c.i

SnolfMania/Objects/Player.s: SnolfMania/Objects/Player.c.s
.PHONY : SnolfMania/Objects/Player.s

# target to generate assembly for a file
SnolfMania/Objects/Player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Player.c.s
.PHONY : SnolfMania/Objects/Player.c.s

SnolfMania/Objects/Snolf.o: SnolfMania/Objects/Snolf.c.o
.PHONY : SnolfMania/Objects/Snolf.o

# target to build an object file
SnolfMania/Objects/Snolf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Snolf.c.o
.PHONY : SnolfMania/Objects/Snolf.c.o

SnolfMania/Objects/Snolf.i: SnolfMania/Objects/Snolf.c.i
.PHONY : SnolfMania/Objects/Snolf.i

# target to preprocess a source file
SnolfMania/Objects/Snolf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Snolf.c.i
.PHONY : SnolfMania/Objects/Snolf.c.i

SnolfMania/Objects/Snolf.s: SnolfMania/Objects/Snolf.c.s
.PHONY : SnolfMania/Objects/Snolf.s

# target to generate assembly for a file
SnolfMania/Objects/Snolf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Snolf.c.s
.PHONY : SnolfMania/Objects/Snolf.c.s

SnolfMania/Objects/Zone.o: SnolfMania/Objects/Zone.c.o
.PHONY : SnolfMania/Objects/Zone.o

# target to build an object file
SnolfMania/Objects/Zone.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Zone.c.o
.PHONY : SnolfMania/Objects/Zone.c.o

SnolfMania/Objects/Zone.i: SnolfMania/Objects/Zone.c.i
.PHONY : SnolfMania/Objects/Zone.i

# target to preprocess a source file
SnolfMania/Objects/Zone.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Zone.c.i
.PHONY : SnolfMania/Objects/Zone.c.i

SnolfMania/Objects/Zone.s: SnolfMania/Objects/Zone.c.s
.PHONY : SnolfMania/Objects/Zone.s

# target to generate assembly for a file
SnolfMania/Objects/Zone.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/Objects/Zone.c.s
.PHONY : SnolfMania/Objects/Zone.c.s

SnolfMania/dllmain.o: SnolfMania/dllmain.c.o
.PHONY : SnolfMania/dllmain.o

# target to build an object file
SnolfMania/dllmain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/dllmain.c.o
.PHONY : SnolfMania/dllmain.c.o

SnolfMania/dllmain.i: SnolfMania/dllmain.c.i
.PHONY : SnolfMania/dllmain.i

# target to preprocess a source file
SnolfMania/dllmain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/dllmain.c.i
.PHONY : SnolfMania/dllmain.c.i

SnolfMania/dllmain.s: SnolfMania/dllmain.c.s
.PHONY : SnolfMania/dllmain.s

# target to generate assembly for a file
SnolfMania/dllmain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnolfMania.dir/build.make CMakeFiles/SnolfMania.dir/SnolfMania/dllmain.c.s
.PHONY : SnolfMania/dllmain.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SnolfMania"
	@echo "... GameAPI/C/GameAPI/Game.o"
	@echo "... GameAPI/C/GameAPI/Game.i"
	@echo "... GameAPI/C/GameAPI/Game.s"
	@echo "... SnolfMania/Objects/HUD.o"
	@echo "... SnolfMania/Objects/HUD.i"
	@echo "... SnolfMania/Objects/HUD.s"
	@echo "... SnolfMania/Objects/Player.o"
	@echo "... SnolfMania/Objects/Player.i"
	@echo "... SnolfMania/Objects/Player.s"
	@echo "... SnolfMania/Objects/Snolf.o"
	@echo "... SnolfMania/Objects/Snolf.i"
	@echo "... SnolfMania/Objects/Snolf.s"
	@echo "... SnolfMania/Objects/Zone.o"
	@echo "... SnolfMania/Objects/Zone.i"
	@echo "... SnolfMania/Objects/Zone.s"
	@echo "... SnolfMania/dllmain.o"
	@echo "... SnolfMania/dllmain.i"
	@echo "... SnolfMania/dllmain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

